name: miEPG (solo ES, diario)

on:
  workflow_dispatch:
  schedule:
    # 02:00 Europe/Madrid = 00:00 UTC (CEST)
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparar herramientas
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl wget gzip sed

      - name: Mostrar fuentes y canales ES
        run: |
          echo "== countries/es/epgs.txt =="
          cat countries/es/epgs.txt || true
          echo
          echo "== countries/es/canales.txt =="
          cat countries/es/canales.txt || true

      - name: Construir EPG ES
        run: |
          chmod +x .github/workflows/EPG_script.sh
          .github/workflows/EPG_script.sh \
            countries/es/epgs.txt \
            countries/es/canales.txt \
            miEPG_ES.xml

      - name: Comprobar resultado (conteos)
        run: |
          test -s miEPG_ES.xml || { echo "miEPG_ES.xml está vacío"; exit 12; }
          echo "Primeras 40 líneas:"
          head -n 40 miEPG_ES.xml || true
          echo
          echo "Programmes totales:"
          grep -c "<programme" miEPG_ES.xml || echo 0

      - name: Publicar en repo público (solo ES)
        if: success()
        env:
          GH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          TMPDIR=$(mktemp -d)
          cd "$TMPDIR"
          git config --global user.email "bot@github"
          git config --global user.name  "epg-bot"
          git clone "https://github.com/JoomBall/miEPG-pub.git"
          cd miEPG-pub

          mkdir -p es
          cp "${GITHUB_WORKSPACE}/miEPG_ES.xml" "es/miEPG_ES.xml"

          git add -A
          git commit -m "update: ES $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || { echo "Nada que commitear"; exit 0; }
          git push "https://x-access-token:${GH_TOKEN}@github.com/JoomBall/miEPG-pub.git" HEAD:main
