name: Test Simple EPG Generation

on:
  workflow_dispatch:
    inputs:
      country:
        description: 'Country to test (us or au)'
        required: true
        default: 'us'
        type: choice
        options:
        - us
        - au

permissions:
  contents: write

jobs:
  test-epg:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl wget gzip sed

      - name: Test Simple EPG Generation
        run: |
          chmod +x .github/workflows/simple_epg.sh
          .github/workflows/simple_epg.sh "${{ github.event.inputs.country }}"

      - name: Commit if successful
        run: |
          COUNTRY="${{ github.event.inputs.country }}"
          EPG_FILE="countries/$COUNTRY/EPG.xml"
          
          if [ -f "$EPG_FILE" ]; then
            PROGRAMMES=$(grep -c "<programme" "$EPG_FILE" || echo 0)
            if [ "$PROGRAMMES" -gt 0 ]; then
              git config --global user.email "actions@github.com"
              git config --global user.name "github-actions[bot]"
              git add "$EPG_FILE"
              git commit -m "test: generate EPG for $COUNTRY - $PROGRAMMES programmes"
              git push
              echo "✅ Successfully generated EPG with $PROGRAMMES programmes"
            else
              echo "⚠️ EPG generated but no programmes found"
            fi
          else
            echo "❌ No EPG file generated"
          fi
